# F5-TTS | E2-TTS
model = "F5-TTS"
ref_audio = "/home/vision/Documents/RodSerling_audio_isolated.wav"
# If an empty "", transcribes the reference audio automatically.
ref_text = ""
gen_text = "In a hole in the ground there lived a hobbit. Not a nasty, dirty, wet hole, filled with the ends of worms and an oozy smell, nor yet a dry, bare, sandy hole with nothing in it to sit down on or to eat: it was a hobbit-hole, and that means comfort."
# File with text to generate. Ignores the text above.
gen_file = ""
remove_silence = false
output_dir = "tests"